version: '3.3'

services:
  apache:
    image: php:7.4.33-apache  # Gunakan PHP 7.4.33 dengan Apache
    container_name: lampp_php7.4.33_apache
    ports:
      - ${APACHE_PORT}:80  # Gunakan port dari .env
    volumes:
      - ${APP_DIR}:/var/www/html  # Bind mount project Anda ke dalam Apache
    depends_on:
      - mysql
    networks:
      - lampp-net

  mysql:
    image: mysql:latest
    container_name: lampp_php7.4.33_mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - lampp-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lampp_php7.4.33_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - lampp-net

networks:
  lampp-net:
    driver: bridge
