version: '3.3'

services:
  apache:
    image: php:8.0-apache  # Gunakan PHP 8.0 dengan Apache
    container_name: lampp_php8.0_apache
    ports:
      - "${APACHE_PORT}:80"  # Gunakan port dari .env
    volumes:
      - ${APP_DIR}:/var/www/html  # Bind mount direktori proyek Anda ke Apache
    depends_on:
      - mysql
    networks:
      - lampp8.0-net

  mysql:
    image: mysql:latest
    container_name: lampp_php8.0_mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - lampp8.0-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lampp_php8.0_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - lampp8.0-net

networks:
  lampp8.0-net:
    driver: bridge
